"""
src/recommendation_system/tool.py

Agentic Tool wrapper for urban tree recommendations in Egypt.
Provides a Pydantic input schema and a robust, callable tool function
for LLM Agents to query the TreeRecommendationEngine.
"""

from __future__ import annotations

import logging
from typing import Any, Dict, Optional, Union
from pydantic import BaseModel, Field

from .engine import TreeRecommendationEngine

# Configure logger with strict minimum logging level INFO
logger = logging.getLogger("Zar3a.TreeRecommendationTool")
if not logger.handlers:
    handler = logging.StreamHandler()
    formatter = logging.Formatter("[%(asctime)s] [%(name)s] [%(levelname)s] %(message)s")
    handler.setFormatter(formatter)
    logger.addHandler(handler)
logger.setLevel(logging.INFO)

# Initialize the engine instance (utilizes the Singleton pattern)
engine = TreeRecommendationEngine()


class TreeFilterInput(BaseModel):
    """
    Schema for filtering and recommending urban trees in Egypt based on spatial and climate constraints.
    """
    narrow_street: bool = Field(
        default=False, 
        description="True if the target location is a narrow street requiring sidewalk-safe roots (Deep root systems)."
    )
    water_requirement: str = Field(
        default="Low", 
        description="Water availability constraint. Options: 'Low', 'Medium', or 'High'."
    )
    min_cooling_score: int = Field(
        default=5, 
        description="Minimum required cooling score from 1 to 10 based on urban heat island severity."
    )
    top_n: int = Field(
        default=3, 
        description="Number of top tree recommendations to return."
    )


def recommend_trees_tool(criteria: Optional[Union[Dict[str, Any], TreeFilterInput]] = None) -> str:
    """
    Tool function invoked by the Agent to retrieve suitable urban tree recommendations in Egypt.
    
    Args:
        criteria (dict | TreeFilterInput | None): Filter parameters generated by the LLM.
        
    Returns:
        str: JSON formatted string containing the top recommended trees,
             or a helpful guidance string if no matching trees were found.
    """
    # 1. Normalize input criteria to dictionary
    if criteria is None:
        criteria_dict: Dict[str, Any] = {}
    elif isinstance(criteria, BaseModel):
        criteria_dict = criteria.model_dump()
    elif isinstance(criteria, dict):
        criteria_dict = criteria.copy()
    else:
        logger.warning(
            "Unexpected criteria type received: %s. Attempting dictionary conversion.",
            type(criteria),
        )
        try:
            criteria_dict = dict(criteria)
        except Exception as exc:
            logger.error("Failed to convert criteria to dict: %s. Using empty criteria.", exc)
            criteria_dict = {}

    logger.info("recommend_trees_tool invoked with criteria: %s", criteria_dict)

    top_n = criteria_dict.get("top_n", 3)
    try:
        top_n = max(1, int(top_n))
    except (ValueError, TypeError):
        top_n = 3

    # 2. Query the recommendation engine
    result_df = engine.recommend(criteria=criteria_dict, top_n=top_n)

    # 3. Handle empty results
    if result_df.empty:
        logger.warning(
            "recommend_trees_tool found no matching trees for criteria: %s",
            criteria_dict,
        )
        return "No matching trees found with these strict constraints. Try relaxing water or cooling requirements."

    # 4. Convert the resulting DataFrame to JSON string (preserving Arabic characters)
    logger.info(
        "recommend_trees_tool successfully returning %d tree recommendation(s).",
        len(result_df),
    )
    return result_df.to_json(orient="records", force_ascii=False)


def get_recommend_trees_tool_spec() -> Dict[str, Any]:
    """
    Generates a standard OpenAI / LangChain / Agent function tool specification.
    """
    return {
        "type": "function",
        "function": {
            "name": "recommend_trees_tool",
            "description": (
                "Recommends suitable urban trees for planting in Egypt based on spatial constraints "
                "(narrow streets / sidewalk-safe deep roots), water availability ('Low', 'Medium', 'High'), "
                "and microclimate cooling requirements."
            ),
            "parameters": TreeFilterInput.model_json_schema(),
        },
    }